### ISSUE TITLE
[Bug]: The fixed "Optimize text should hidden and only display while scrolling

### ISSUE THREAD

**Issue by taorepoara** [lenra-io/website#79]
### What happened?

In [the feature section of the discover page](https://www.lenra.io/discover.html#features), a text is fixed to scroll with the user.

This text should be hidden at the top and end of the section but it's not on Chrome. Works fine on Firefox.

It would be better if it was sticky.

### What browsers are you seeing the problem on?

Chrome (or chrome-based)

### Version

112

**Comment by adityarawat1223** [comment]
can i work on this ?

**Comment by taorepoara** [comment]
> can i work on this ?

Yes of course !

I'll assign you the issue. Let me know if you need help.

**Comment by adityarawat1223** [comment]
can i know which text i need to fix ?

**Comment by taorepoara** [comment]
@adityarawat1223 On this page: https://www.lenra.io/discover.html#features on Chrome base browsers the text `Our mission in one word: Optimize` (or just `Optimize` in mobile design) is always displayed instead of only display when scrolling

**Comment by taorepoara** [comment]
> @adityarawat1223 On this page: https://www.lenra.io/discover.html#features on Chrome base browsers the text `Our mission in one word: Optimize` (or just `Optimize` in mobile design) is always displayed instead of only display when scrolling

I've just tried on the latest Chrome version and it seems to be fixed in Chrome 117.

I close this issue since the problem was a Chrome browser one. Sorry.
